name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to GHCR.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.TOKEN }}
      
    - name: Filter client changes
      id: client-filter
      uses: dorny/paths-filter@v3
      with:
        filters: |
          client/**
          !client/**

    - name: Build and push frontend image
      if: ${{ steps.client-filter.outputs.matched == 'true' }}
      run: |
        cd client/
        docker build -t plateau-frontend:latest .
        docker tag plateau-frontend:latest ghcr.io/zeyxs/plateau-frontend:latest
        docker push ghcr.io/zeyxs/plateau-frontend:latest

    - name: Filter server changes
      id: server-filter
      uses: dorny/paths-filter@v3
      with:
        filters: |
          server/**
          !server/**

    - name: Build and push backend image
      if: ${{ steps.server-filter.outputs.matched == 'true' }}
      run: |
        cd server/
        docker build -t plateau-backend:latest .
        docker tag plateau-backend:latest ghcr.io/zeyxs/plateau-backend:latest
        docker push ghcr.io/zeyxs/plateau-backend:latest
